### ISSUE TITLE
Remove requirement to specify a staging bucket.

### ISSUE THREAD

**Issue by thirteen37** [gojek/feast#177]
**Is your feature request related to a problem? Please describe.**
Some APIs require a staging bucket to be provided and specified, making it necessary for the user's code to deal with the complexities of GCS.

**Describe the solution you'd like**
The staging bucket (which is temporary) should be handled transparently by the API, similar to how the BEAM API does this.

**Comment by davidheryanto** [comment]
To be more specific, this issue is regarding Feast Python SDK when using Feast to write / read data from Feast warehouse.

There are 2 kinds of operations in Feast when a staging location may be needed currently:
1. Retrieving a training dataset
2. Running an import job

Example for operation 1:
```python
dataset = feast_client.download_dataset_to_df(
  dataset_info, 
  staging_location="gs://staging-location")
```

Example for operation 2:
```python
importer = Importer.from_df(df_complete, 
                            entity='ride', 
                            owner='user@website.com',  
                            staging_location=STAGING_LOCATION,
                            id_column='ride', 
                            timestamp_column='pickup_datetime')
```

In order to remove `staging_location` parameter in the Python SDK without changing the existing GRPC and data types proto definition, I'm thinking of making use of warehouse storage spec data retrieved from Core. This warehouse storage spec data contains information about the Google project the warehouse resides in and/or the `templocation` configured.

**TODO**: Provide example warehouse storage spec data

If `templocation` exists, then Feast Python SDK will use this as the staging location, if not, then Feast Python SDK will make use of the project info to assume the use of  
```
gs://[optional_prefix]_[project_id]_[optional_suffix]
```
as the staging location


**Future improvement**:
- I believe a better approach is that the handling of this staging location or temporary data should be handled by Feast Core (vs Feast Python SDK), _similar to how Python SDK for BigQuery works_.   
But this requires updates in the proto spec and Feast Core implementations. So for a quick fix, I think the abovementioned approach is better.

**Comment by woop** [comment]
This approach does not feel clean. The staging location should be hardcoded for a specific deployment of Feast. I also don't think there should be an assumed location as above. 

When the client makes a request for data, Core should return the correct information (bucket/object path) which it can then use to download the data from. I don't see the need for a storage spec here.

**Comment by irvifa** [comment]
I think it's better to use a hardcoded value for the staging, given the fact that the core should return correct information. Providing a spec isn't a clean way to do so, IMHO.
