### ISSUE TITLE
DataFlow throws out " java.io.FileNotFoundException: No files matched spec: bucket/ingestion_1.csv" while executing

### ISSUE THREAD

**Issue by quantum109678** [gojek/feast#212]
### Specifications

- Version:
- Platform:
- Subsystem:

**Comment by davidheryanto** [comment]
Hi @quantum109678 
Can you describe the steps you do to reproduce your error?

Did you encounter it by following the steps here?
https://github.com/gojek/feast/blob/master/docs/install.md

In these lines
```
.....
# Make sure this bucket has been created
FEAST_STAGING_LOCATION_GCS_URI=gs://bucket
```

You are supposed to replace "bucket" with whatever existing bucket you have and owned in Google Cloud Storage e.g.

If you don't have any existing bucket, you can create a new one. For example to create a bucket called "mybucket20190612-1524" you can run this command (make sure you have installed Google Cloud SDK):
```
gsutil mb gs://mybucket20190612-1524
```

Then you can set the variable `FEAST_STAGING_LOCATION_GCS_URI` like so:
```
FEAST_STAGING_LOCATION_GCS_URI=gs://mybucket20190612-1524
```

**Comment by quantum109678** [comment]
Yes I followed the steps according to [https://github.com/gojek/feast/blob/master/cli/README.md]
I have created my bucket and set the variable FEAST_STAGING_LOCATION_GCS_URI appropriately.
When I run **feast jobs run /tmp/feast-batch-import.yaml --wait** , the job runs for sometime and then throws an error. I checked the Job Log and then discovered the **java.io.FileNotFoundException: No files matched spec: bucket/ingestion_1.csv** error from the DataFlow dashboard.

**Comment by davidheryanto** [comment]
Can you make sure that the source file referenced in the import spec exists?
If you open up the ingestion spec file e.g. in your case `/tmp/feast-batch-import.yaml`, you will see the value for `sourceOptions.path`is the gcs uri to your csv file.

For example, if the ingestion spec sourceOptions is like so
```
...
sourceOptions:
  path: gs://my-feast-bucket/ingestion_1.csv
...
```
Can you check with Google Cloud Console or gsutil that this file at `gs://my-feast-bucket/ingestion_1.csv`  exists and you and your Dataflow jobs have read access to this file?

If not, then you'll need to upload this `ingestion_1.csv` file into `gs://my-feast-bucket/` first before running the import job.

The error you mention seems to be because the file does not exist in GCS.

**Comment by quantum109678** [comment]
The name of my bucket and the projectID were the same...this was probably the cause of the error. When I created another bucket with a different name and tried, it worked just fine. I still do not understand why my first approach threw out that error.

**Comment by davidheryanto** [comment]
Without more details, it's quite difficult for us to figure out the root cause.

If you can list out the steps/command that you run and the output of each step, then it's easier to debug because we can try to _reproduce_ your issue.

Else I think we can close this issue, because there is not enough info to *reproduce* the problem.

**Comment by quantum109678** [comment]
Thanks a lot. Deleting the previous Redis instances worked fine.
