### ISSUE TITLE
Docker compose for Feast

### ISSUE THREAD

**Issue by woop** [gojek/feast#272]
We've had requests for a Docker Compose script to initialize a Feast deployment. This would make it easier for Non-Kube based deployment, especially during quickstarts or tests.

The proposed use case here is for a single `docker-compose up` to bring up a running Feast deployment. It should minimally include

- Redis
- Kafka
- Feast Core
- Feast Core DB
- Feast Serving

The default configuration can be used for these components. The existing Helm installation can be used for reference.

**Comment by khorshuheng** [comment]
As discussed, i will start working on this.

**Comment by ches** [comment]
We have this done, although it is probably _more_ than what many people developing on the project would want all the time because it includes containers for dev with Cassandra and Hive as well. We could structure a base `docker-compose.yml` with the components given above, and an extra one or two for extending the base if developing/testing for those storage options.

**Comment by woop** [comment]
This is resolved in #328
