### ISSUE TITLE
BigQuery dependency for write failures

### ISSUE THREAD

**Issue by smadarasmi** [gojek/feast#300]
It seems like the dependency on BigQuery is not entirely removed from the project. We are writing failed elements to dead letter table in BigQuery https://github.com/gojek/feast/blob/0.3-dev/ingestion/src/main/java/feast/ingestion/ImportJob.java#L119

Could we perhaps store the failed writes in a cache/store? Or allow for other warehouse to store them?

**Comment by woop** [comment]
I'd love to support a generic cache store here instead of BQ. Right now this BQ dependency is optional though, so it's not a hard requirement for running the systems. So we can consider it to be "unimplemented" for the time being.

It's unlikely that we would prioritze this in the short term, but I don't think it would be too much work to implement.
