### ISSUE TITLE
[chore] Make v0.3.7 release, publish artifacts for v0.3.6 also

### ISSUE THREAD

**Issue by ches** [gojek/feast#442]
v0.3.6 has been tagged, but artifacts are not on Maven Central.

I believe the only changes since 0.3.6 are #360 and #426/#407, but a new release would be helpful for us, we need the `datatypes-java` module published.

**Comment by woop** [comment]
> v0.3.6 has been tagged, but artifacts are not on Maven Central.

Is this due to the release automation landing after 0.3.6, or is something wrong?

> I believe the only changes since 0.3.6 are #360 and #426/#407, but a new release would be helpful for us, we need the `datatypes-java` module published.

Makes sense. We can pick that up early this week.

**Comment by ches** [comment]
> Is this due to the release automation landing after 0.3.6, or is something wrong?

Yes, I believe it's because the release automation came to the v0.3 series branch after 0.3.6.

Although, @davidheryanto I see the Prow config has the filter to match branches/tags that look like a version—will it trigger when a tag object is pushed, or does there need to be a PR? It looks like we try to set `REVISION` from pull request base, is that going to work as desired?

**Comment by ches** [comment]
Note: probably also from timing of when things landed, HEAD of v0.3-branch has `<revision>0.3.6-SNAPSHOT</revision>` in the POM, it should be 0.3.7-SNAPSHOT now since we're past 0.3.6 final. We can fix this in the course of this ticket.

**Comment by davidheryanto** [comment]
Hi @ches yes the pushing of artifacts will be triggered whenever a new branch or tag (with a name that match the semantic versioning regex) is pushed. 

It does not require a pull request, but I think it's good to do so, because currently the end to end test will only run on pull request (I currently make an assumption that whenever a new tag or branch is pushed on the main Feast repository, it has passed the integration test, so the artifacts publishing step will skip the end to end test).

Will pick up some time this week the publishing of Artifacts for Feast v0.3.7 and v0.3.6

**Comment by ches** [comment]
> in case of `v0.3.7`, we should probably make a pull request to backport some commits to `v0.3-branch`

Are there some that you have in mind?

I created an in issue label yesterday called `backport-candidate`, we may be one of the primary stakeholders interested in backports to v0.3 at this point but it'd be great if all maintainers could pitch in to applying it to PRs that seem appropriate. My thinking was to be able to filter closed issues to review these, as it's a challenge for us to keep up with every change that's coming through to catch bug fixes, etc. that might be important.

**Comment by ches** [comment]
Thanks for the answers about the automation by the way!

**Comment by ches** [comment]
Okay, it's come time that I need to ask for help for completing either this one or #476—I'm not certain if I have complete information to do this self-service and with the access rights I have.

@woop @davidheryanto @zhilingc @khorshuheng

**Comment by woop** [comment]
I'm trying to figure out what all the missing pieces are here. @ches is it possible for you to enumerate your uncertainties? Or if you have certainties (like access you need) then you could also let me know and I will try to address them.

I definitely want both #442 and #472 to be completed successfully.

**Comment by davidheryanto** [comment]
Hi @ches sorry for the slow reponse.
Feast Java SDK v0.3.6 is not published to Maven central because when it was tagged, the CI jobs for v0.3-branch do not `publish-java-sdk` step yet. 

I will manually publish Java SDK for v0.3.6 today.

For subsequent releases in v0.3, the CI jobs have already configured  `publish-java-sdk` so the Java SDK will be available in Maven central.

Do we want to release `v0.3.7  based on the current state of `v0.3-branch`?

**Comment by ches** [comment]
Closed by #670.

Modules like `feast-sdk` for Java were published for v0.3.6 by @davidheryanto back in March as noted in the previous comment here, others for v0.3.7 including `datatypes-java` which was newly added in this release are on Maven Central now.

Thanks everyone!
