### ISSUE TITLE
Add details about of GCP minimum specifications

### ISSUE THREAD

**Issue by imjuanleonard** [gojek/feast#573]
## Expected Behavior 
When I create a clean GCP project and follow the feast installation guide on GKE, everything should go smoothly without hiccups

## Current Behavior
When I set up the feast for the first time using my personal account, I encounter some trivialities along the way, for example:
-> Need to scale the Resource Quota
-> Need to create a default network
-> Some tweak around service account permission

## Steps to reproduce
-> Follow the feast GKE install 

## Possible Solution
-> Document along the way minimum GCP requirement, and update any required steps on feast docs

**Comment by woop** [comment]
> When I create a clean GCP project and follow the feast installation guide on GKE, everything should go smoothly without hiccups

This description is too vague. Another way of saying it is "I shouldn't have problems". Please try to add more context.

> Need to scale the Resource Quota
Can you please link to or be specific with this problem?

> Need to create a default network
Can you please describe the problem you were facing with the default network or lack thereof?

> Some tweak around service account permission
Please provide us with the problem so that we can help to address it.

I am closing this issue for now. Please reopen it with the correct information.
